[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_GOOGLE_OAUTH_CLIENT_ID = "974301831607-5svojrrjj2i39k9ia5386o4opb27ihu9.apps.googleusercontent.com"

[[redirects]]
  from = "/oauth2callback"
  to = "/.netlify/functions/auth"
  status = 200